workflow:
  rules:
      - changes:
          - srstest2/**/*
stages:
  - build

image: alpine

build_a:
  stage: build
  script:
    - echo "This job builds something quickly."
    - echo "I am in srstest2"
trigger_project:
  stage: build
  trigger:
      project: srsgrouptest/srstest-trigger
      
trigger_main:
  stage: build
  trigger:
    include:
      local: '/srstest/.gitlab-ci.yml'

